/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:f60fc785-7c2a-4ff1-80c7-6c3508331047",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_nVxhha3vp",
    "aws_user_pools_web_client_id": "5f9191m35i2cjfprjfahvd74lo",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "api",
            "endpoint": "https://mf08nmszxc.execute-api.ap-southeast-1.amazonaws.com/dev",
            "region": "ap-southeast-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://l5viims64fbnxmt3jtdmtofmuu.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qonbwyeecnb7vf3cz4rgktybeq"
};


export default awsmobile;
